### ISSUE TITLE
How to Raise event on delay?

### ISSUE THREAD

**Issue by mikeypdev** [gwiazdorrr/EventBetter#2]
Thanks for this event system. It's fantastic.

I have a need to schedule events on a delay. I created a "partial" class to handle this, which seems to work fine, but I'm not sure if this is the best approach.

```
using System.Threading.Tasks;

public static partial class EventBetter
{

    public static async void RaiseNextFrame<MessageType>(MessageType message) { 

        await Task.Delay(10).ContinueWith(x => {RaiseInternal(message);}, TaskScheduler.FromCurrentSynchronizationContext());
    
    }

    public static async void RaiseDelayed<MessageType>(MessageType message, int delay) {

        await Task.Delay(delay).ContinueWith(x => {RaiseInternal(message);}, TaskScheduler.FromCurrentSynchronizationContext());

    }

}
```

Does this look like a reasonable way to support delayed events?

Thanks again for this awesome system.

**Comment by gwiazdorrr** [comment]
Hi, this may be absolutely fine in your case, but it definitely allocates - for instance, the delegate passed to `ContinueWith`. I'd like to keep EB event raising alloc-free.

That said, I think the library could benefit from embracing Unity's PlayerLoopSystem - execution could then be easily scheduled at great precision, with no-alloc approach possible.
